// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecurityDoors.DataAccessLayer.Models;

namespace SecurityDoors.DataAccessLayer.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190528091235_Altered Card Table")]
    partial class AlteredCardTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SecurityDoors.DataAccessLayer.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment");

                    b.Property<int>("Status");

                    b.Property<string>("UniqueNumber");

                    b.HasKey("Id");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("SecurityDoors.DataAccessLayer.Models.Door", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Doors");
                });

            modelBuilder.Entity("SecurityDoors.DataAccessLayer.Models.DoorPassing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DoorId");

                    b.Property<DateTime>("PassingTime");

                    b.Property<int>("PersonId");

                    b.HasKey("Id");

                    b.HasIndex("DoorId");

                    b.HasIndex("PersonId");

                    b.ToTable("DoorPassings");
                });

            modelBuilder.Entity("SecurityDoors.DataAccessLayer.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CardId");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<bool>("Gender");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Passport")
                        .IsRequired();

                    b.Property<string>("SecondName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CardId")
                        .IsUnique()
                        .HasFilter("[CardId] IS NOT NULL");

                    b.ToTable("People");
                });

            modelBuilder.Entity("SecurityDoors.DataAccessLayer.Models.DoorPassing", b =>
                {
                    b.HasOne("SecurityDoors.DataAccessLayer.Models.Door", "Door")
                        .WithMany("DoorPassings")
                        .HasForeignKey("DoorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SecurityDoors.DataAccessLayer.Models.Person", "Person")
                        .WithMany("DoorPassings")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SecurityDoors.DataAccessLayer.Models.Person", b =>
                {
                    b.HasOne("SecurityDoors.DataAccessLayer.Models.Card", "Card")
                        .WithOne("Person")
                        .HasForeignKey("SecurityDoors.DataAccessLayer.Models.Person", "CardId");
                });
#pragma warning restore 612, 618
        }
    }
}
