// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecurityDoors.DataAccessLayer.Models;

namespace SecurityDoors.DataAccessLayer.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190524090535_FirstVersionOfDatabase")]
    partial class FirstVersionOfDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SecurityDoors.DataAccessLayer.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PersonId");

                    b.Property<bool>("Status");

                    b.Property<string>("UniqueNumber");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("SecurityDoors.DataAccessLayer.Models.Door", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("InOut");

                    b.Property<DateTime>("PersonEnter");

                    b.HasKey("Id");

                    b.ToTable("Doors");
                });

            modelBuilder.Entity("SecurityDoors.DataAccessLayer.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DoorId");

                    b.Property<string>("FirstName");

                    b.Property<bool>("Gender");

                    b.Property<string>("LastName");

                    b.Property<string>("Passport");

                    b.Property<string>("SecondName");

                    b.HasKey("Id");

                    b.HasIndex("DoorId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("SecurityDoors.DataAccessLayer.Models.Card", b =>
                {
                    b.HasOne("SecurityDoors.DataAccessLayer.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SecurityDoors.DataAccessLayer.Models.Person", b =>
                {
                    b.HasOne("SecurityDoors.DataAccessLayer.Models.Door", "Door")
                        .WithMany()
                        .HasForeignKey("DoorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
